services:
  db:
    container_name: taxmanager-db
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxmanager
      PGDATA: /data/postgres
    ports:
      - "5435:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
